// skills (Users)
export const ADD_SKILL_TO_USER = "ADD_SKILL_TO_USER"
export const ADD_MULTIPLE_SKILLS_TO_USER = "ADD_MULTIPLE_SKILLS_TO_USER"
export const REMOVE_SKILL_FROM_USER = "REMOVE_SKILL_FROM_USER"
export const UPDATE_SKILL_OF_USER = "UPDATE_SKILL_OF_USER";

// Needed skills (Project)
export const ADD_SKILL_TO_PROJECT = "ADD_SKILL_TO_PROJECT"
export const ADD_MULTIPLE_SKILLS_TO_PROJECT = "ADD_MULTIPLE_SKILLS_TO_PROJECT"
export const REMOVE_SKILL_FROM_PROJECT = "REMOVE_SKILL_FROM_PROJECT"
export const UPDATE_SKILL_FOR_PROJECT = "UPDATE_SKILL_FOR_PROJECT";